### ISSUE TITLE
关于Python2.7的默认编码方式导致SyntaxError的问题

### ISSUE THREAD

**Issue by GamerNoTitle** [GamerNoTitle/Hitokoto-Spider#5]
@TheBaiRuo汇报：在Python2.7的环境下，运行程序出现如下BUG信息

---
 File "main.py", line 11
SyntaxError: Non-ASCII character '\xe6' in file main.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Traceback (most recent call last):
  File "main.py", line 48, in <module>
    create_csv(path)
  File "main.py", line 14, in create_csv
    with open(path,"w+",newline="",encoding="utf8") as file:    # 鎵撳紑鏂囦欢锛屼篃鐩稿綋浜庝竴涓洖杞︼紝閬垮厤瑕嗙洊鏂囨。

**Comment by GamerNoTitle** [comment]
初步判定为Python2.7的默认编码方式为Unicode而导致的问题，针对这种问题，可以在文件的头头加入以下的内容
```python
# -*- coding: utf-8 -*-  
```
如果你有更好的方法，可以在这条issue下面留言，这条issue将持续开放

**Comment by GamerNoTitle** [comment]
目前发现在腾讯的的webIDE平台CloudStudio中也会出现这个问题
